version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: docker_db_test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    restart: unless-stopped

  pgadmin:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_LOGIN_BANNER: "Authorized users only!"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "10"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_LISTEN_PORT: "5050"
      PGADMIN_CONFIG_DEFAULT_SERVER: "0.0.0.0"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ../postgresql:/var/lib/pgadmin/storage/admin_example.com/postgresql_scripts:ro

    ports:
      - "5050:5050"
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: