version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_test  
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    build: .  # Build from the Dockerfile in the current directory
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ../postgresql:/postgresql_scripts:z  # Mount your SQL directory here

volumes:
  pgdata:
